### ISSUE TITLE
Crash with util.BuildQueryBytes upon nil options from query

### ISSUE THREAD

**Issue by sreekanth-cb** [couchbase/n1fty#4]
Looks like the Options field in FTSSearchInfo is optional and current implementation crashes here:
https://github.com/couchbase/n1fty/blob/master/index.go#L196 upon leaving this field empty from query.

Another thing noted is,

May be it's better/cleaner to take `FTSSearchInfo` as the argument to BuildQueryBytes and perform the input validations inside it.

My understanding was that the  BuildQueryBytes should create the native bleve query bytes. 
At least, my trials didn't shown it that way.

It would be great to have  test cases which does a queryBytes/query comparison between natural/original bleve queries constructed as against that created over BuildQuery.

**Comment by abhinavdangeti** [comment]
I decided not to move FTSSearchInfo into BuildQueryBytes to not add query dependencies within util/.

By native query bytes do you mean in case of a query string, just show:

        {"query": {"query": "blah blah"}}

The reason this isn't enough is because of the explicit field argument, which needs to be applied to sub queries if in case they don't have a fully qualified field (query_string++ if you will).

The query_builder as of today will build a proper query (query string query will be converted into a boolean query) and the field will be applied to subqueries whose field isn't explicitly set (for e.g. +engineering as opposed to +dept:engineering).

http://review.couchbase.org/#/c/104710/
